#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_KEY_CONTENT}

package_update: true
package_upgrade: true

packages:
  - fail2ban
  - ufw
  - podman
  - python3
  - python3-pip
  - python3-venv

runcmd:
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable ssh
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - ufw allow 'OpenSSH'
  - ufw allow http
  - ufw allow https
  - ufw --force enable
  - sed -ie '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -ie '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -ie '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding yes/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers devops' /etc/ssh/sshd_config
  - systemctl restart ssh
  - sudo systemctl enable --now cni-dhcp.socket
  - mkdir -p /home/devops/apps
  - chown -R devops:devops /home/devops/apps
  - sudo -u devops pip3 install --user uvx
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - echo 'export PATH="$HOME/.local/bin:$PATH"' | sudo -u devops tee -a /home/devops/.bashrc
  - echo 'export PATH="$HOME/.local/bin:$PATH"' | sudo -u devops tee -a /home/devops/.profile
